name: Pillbox
options:
  bundleIdPrefix: com.shimondeitel.suppltrack
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Pillbox:
    type: application
    platform: iOS
    sources:
      - path: Pillbox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.suppltrack
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Pillbox/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  PillboxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PillboxTests
      - path: Pillbox.storekit
    dependencies:
      - target: Pillbox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.suppltrack.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  PillboxUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PillboxUITests
    dependencies:
      - target: Pillbox
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.suppltrack.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Pillbox:
    build:
      targets:
        Pillbox: all
        PillboxTests: [test]
        PillboxUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Pillbox.storekit
    test:
      config: Debug
      storeKitConfiguration: Pillbox.storekit
      targets:
        - PillboxTests
        - PillboxUITests
    archive:
      config: Release
